### PR TITLE
Pr/1

### PR DESCRIPTION
**Pull request by bigyihsuan**
I tried to resolve the conflicts, but I don't know if I did it correctly.

### CODE REVIEW

**Comment by bigyihsuan** [comment]
It says that there's conflicts, but not where.

**Comment by Dominik-O22** [comment]
are you using the git desktop application or just the online site?

**Comment by bigyihsuan** [comment]
Desktop app.

**Comment by Dominik-O22** [comment]
then it should show in yellow in the changes tab all the conflict files

**Pull request merged**
